# Generated by Django 2.0.1 on 2021-09-09 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggeduser', models.CharField(max_length=50)),
                ('foodname', models.CharField(max_length=50)),
                ('foodpic', models.ImageField(upload_to='')),
                ('quantity', models.CharField(default='food amount', max_length=30)),
                ('contactno', models.CharField(max_length=10)),
                ('location', models.TextField(default='enter the address')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
                ('foodpic', models.ImageField(upload_to='')),
                ('quantity', models.CharField(default='food amount', max_length=30)),
                ('contactno', models.CharField(max_length=10)),
                ('location', models.TextField(default='enter the address')),
                ('city', models.CharField(max_length=50)),
                ('loggeduser', models.CharField(max_length=50)),
                ('foodcreateuser', models.CharField(max_length=50)),
                ('deliverycontact', models.CharField(max_length=10)),
                ('deliverymail', models.EmailField(max_length=254)),
                ('deliveryaddress', models.TextField(default='enter the address')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
